<a href="https://colab.research.google.com/github/rrl7012005/Tensor-Flow-Computer-Vision-Course/blob/main/Tensors_and_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

#Tensors Introduction

In [ ]:
tensor_3D = tf.constant([

    [[2,3,4.2],
    [4.1,0.7,-3.6]],

    [[0.1, 0.4, -5],
    [6.2, 5.1, -0.3]],

    [[-2.9, 0.7, 1.6],
     [-9.7, 4.4, 2.2]]

], dtype=tf.float32)

print(tensor_3D)

print(tensor_3D.shape)
print(tensor_3D.dtype)

tf.Tensor(
[[[ 2.   3.   4.2]
  [ 4.1  0.7 -3.6]]

 [[ 0.1  0.4 -5. ]
  [ 6.2  5.1 -0.3]]

 [[-2.9  0.7  1.6]
  [-9.7  4.4  2.2]]], shape=(3, 2, 3), dtype=float32)
(3, 2, 3)
<dtype: 'float32'>


Declaring datatype in declaring tensor, brings an error if the dtype doesn't match the elements of the tensor. Thus  use casting method to change the data type. You don't have to declare dtype when declaring tensor as it will default. Its more of a formality.

In [ ]:
casted_tensor_3D = tf.cast(tensor_3D, dtype=tf.int32)
print(casted_tensor_3D)

tf.Tensor(
[[[ 2  3  4]
  [ 4  0 -3]]

 [[ 0  0 -5]
  [ 6  5  0]]

 [[-2  0  1]
  [-9  4  2]]], shape=(3, 2, 3), dtype=int32)


A numpy array can be converted to a tensor. Use the methods list as a guide: https://www.tensorflow.org/api_docs/python/tf


In [ ]:
import numpy as np
np_array = np.array([1,2,3])
tensor = tf.convert_to_tensor(np_array)

print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


eye- Identity tensor

Batch size can be changed into an array. E.g. [2, ] represents 2 batches of 2D tensors. [2, 4] represents a batch size of 2x4 giving a 4D tensor etc. Each batch is a 2D tensor with rows and columns indicated.

In [ ]:
identity = tf.eye(5, num_columns=2, batch_shape=[2, 3], dtype=tf.dtypes.float32)
print(identity)

tf.Tensor(
[[[[1. 0.]
   [0. 1.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[1. 0.]
   [0. 1.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]], shape=(2, 3, 5, 2), dtype=float32)


By default batch_size and num_columns are set to none. You can obtain a more specific tensors by filling all entries with a certain number. The first argument is the shape, the next is the number. Theres also a specific command for filling with 1, called tf.ones but now the 2nd argument is instead the data type (tf.dtypes.float32). You can fill with ones in the same shape as another matrix by just inputting that tensor into the argument. Same thing with tf.zeros and zeros_like.


In [ ]:
nine = tf.fill([1, 2, 4], 9)
print(nine)

one = tf.ones([1, 2, 4], tf.dtypes.float32)
print(one)

one2 = tf.ones_like(tensor_3D)
print(one2)

tf.Tensor(
[[[9 9 9 9]
  [9 9 9 9]]], shape=(1, 2, 4), dtype=int32)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 2, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 2, 3), dtype=float32)


You can return the shape of the tensor as another tensor and rank (same as matrix rank). And size is the number of elements and you can output this number as a float or int using out_type.

In [ ]:
print(tf.shape(one))
tf.rank(one2), tf.size(tensor_3D, out_type=tf.float32)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


(<tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=float32, numpy=18.0>)

Create a randomized tensor, using values of a normal distribution.

first input is shape and every other argument is just automatically assumed but you can change it.

In [ ]:
random = tf.random.normal(
    [2, 4, 7],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random)

tf.Tensor(
[[[-0.7775584  -0.68732744 -0.17085238  1.0447042  -0.59543717
   -2.7913213  -0.597939  ]
  [ 1.2267044   0.30389786 -0.03362191  0.46171632  0.38719705
   -0.13575655 -1.3939846 ]
  [-0.3042363   1.15801    -0.24138272  1.7302349   0.08956157
    0.2130865   0.3000863 ]
  [ 1.8876345  -1.5173038  -0.79857    -0.15440458  0.13925028
    0.51138484 -1.3744308 ]]

 [[-0.37431848 -0.35268104 -0.31708273 -0.28965625 -0.21326295
    0.16679314 -0.03827912]
  [ 0.94507027 -1.1871272   0.03427466  0.42867464 -0.27954018
   -0.33859655 -1.2472597 ]
  [-0.49081835 -0.9661414  -0.19394498 -0.29743454  1.1235945
   -1.1080405   0.44359627]
  [-1.2680994  -0.18571621 -0.32005948  0.13289146 -0.31654206
    0.95404315  1.931665  ]]], shape=(2, 4, 7), dtype=float32)


Can draw from a uniform distribution as well. Max values is 1 by default for floats, but must be specified for ints.

In [ ]:
random2 = tf.random.uniform(
    [2, 3, 5],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random2)

tf.Tensor(
[[[0.5528207  0.45572293 0.6075269  0.7266499  0.9324819 ]
  [0.54221225 0.7929466  0.5007788  0.7522783  0.0449177 ]
  [0.2254368  0.4577824  0.6932833  0.26149368 0.25897908]]

 [[0.30619228 0.31849003 0.65334845 0.27522838 0.38209307]
  [0.708547   0.12088406 0.02671635 0.40003896 0.9132843 ]
  [0.4354571  0.5746273  0.4508332  0.09758592 0.68951774]]], shape=(2, 3, 5), dtype=float32)


Extracting the elements of a tensor by index works similar to an array. Including the [0:4] to return first 4 elements, however the return data structure is a tensor. If do [1:6:2] it goes from index 1 to 6 by jumping 2 elements at a time. : extracts everything. ... extracts everything before/after. can use them interchangeably.

In [ ]:
print(random2[:])
print(random2[:, 2:, 1:3])
print(random2[..., 1])

tf.Tensor(
[[[0.5528207  0.45572293 0.6075269  0.7266499  0.9324819 ]
  [0.54221225 0.7929466  0.5007788  0.7522783  0.0449177 ]
  [0.2254368  0.4577824  0.6932833  0.26149368 0.25897908]]

 [[0.30619228 0.31849003 0.65334845 0.27522838 0.38209307]
  [0.708547   0.12088406 0.02671635 0.40003896 0.9132843 ]
  [0.4354571  0.5746273  0.4508332  0.09758592 0.68951774]]], shape=(2, 3, 5), dtype=float32)
tf.Tensor(
[[[0.4577824 0.6932833]]

 [[0.5746273 0.4508332]]], shape=(2, 1, 2), dtype=float32)
tf.Tensor(
[[0.45572293 0.7929466  0.4577824 ]
 [0.31849003 0.12088406 0.5746273 ]], shape=(2, 3), dtype=float32)


# Math Operations of Tensors


Can apply operations to the whole tensor using tf.math. Can also put complex numbers in a tensor using j.

In [ ]:
tensor = tf.random.normal(
    [3, 2, 2, 2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32
)

print(tensor)

absolute_tensor = tf.abs(tensor)
print(absolute_tensor)

sqrt_tensor = tf.sqrt(tensor)
print(sqrt_tensor)

tf.Tensor(
[[[[-0.6673196   0.16152245]
   [-1.3026185  -1.7902454 ]]

  [[ 0.07767393 -0.6114198 ]
   [-2.2539957   0.20156978]]]


 [[[-1.5473981  -0.12229446]
   [ 0.24614793  0.38473842]]

  [[ 0.86254454 -1.5674287 ]
   [-0.43830547  0.2938043 ]]]


 [[[-0.25307792 -0.9201909 ]
   [ 0.8942041   1.5418025 ]]

  [[ 0.00244554 -0.7260444 ]
   [-1.014719   -1.1934392 ]]]], shape=(3, 2, 2, 2), dtype=float32)
tf.Tensor(
[[[[0.6673196  0.16152245]
   [1.3026185  1.7902454 ]]

  [[0.07767393 0.6114198 ]
   [2.2539957  0.20156978]]]


 [[[1.5473981  0.12229446]
   [0.24614793 0.38473842]]

  [[0.86254454 1.5674287 ]
   [0.43830547 0.2938043 ]]]


 [[[0.25307792 0.9201909 ]
   [0.8942041  1.5418025 ]]

  [[0.00244554 0.7260444 ]
   [1.014719   1.1934392 ]]]], shape=(3, 2, 2, 2), dtype=float32)
tf.Tensor(
[[[[       nan 0.40189856]
   [       nan        nan]]

  [[0.27870044        nan]
   [       nan 0.44896522]]]


 [[[       nan        nan]
   [0.49613297 0.6202729 ]]

  [[0.92873275     

In [ ]:
x_1 = tf.constant([5, 3, 2, 4, 6], dtype=tf.int32)
x_2 = tf.constant([2, 1, 6, 0, -2], dtype=tf.int32)

print(tf.add(x_1, x_2))
print(tf.subtract(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.divide(x_1, x_2))

#Note these are element wise operations only

print(tf.math.divide_no_nan(x_1, x_2)) #Throws 0 if divide by 0 instead of infinity

tf.Tensor([7 4 8 4 4], shape=(5,), dtype=int32)
tf.Tensor([ 3  2 -4  4  8], shape=(5,), dtype=int32)
tf.Tensor([ 10   3  12   0 -12], shape=(5,), dtype=int32)
tf.Tensor([ 2.5         3.          0.33333333         inf -3.        ], shape=(5,), dtype=float64)
tf.Tensor([ 2.5         3.          0.33333333  0.         -3.        ], shape=(5,), dtype=float64)


However if the size is not the same, then you get weird answers but its still element wise operation.

In [ ]:
x_2 = tf.constant([2])
print(tf.add(x_1, x_2)) #Adds each element by 2 as treats x_2 as being stretched out
print(tf.multiply(x_1, x_2)) #Multiplies each element by 2, same treatment as addition

tf.Tensor([7 5 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([10  6  4  8 12], shape=(5,), dtype=int32)


In [ ]:
x_2 = tf.constant([[5], [3], [7]]) #This is 3 different rows
print(tf.add(x_1, x_2)) #So each row is stretched accordingly
print(tf.multiply(x_1, x_2)) #Row 1 * 5, row 2 * 3 etc.

#Stretching occurs until the dimensions match

tf.Tensor(
[[10  8  7  9 11]
 [ 8  6  5  7  9]
 [12 10  9 11 13]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[25 15 10 20 30]
 [15  9  6 12 18]
 [35 21 14 28 42]], shape=(3, 5), dtype=int32)


In [ ]:
# x_2 = tf.constant([7, 2])
# print(tf.add(x_1, x_2))
# # Now you get error because cannot stretch

The maximum/minimum operations compares element by element and returns a new tensor with the maximum of each element. argmax, argmin gives the index of the maximum/minimum value of the whole tensor.

In [ ]:
t1 = tf.random.normal([6])
t2 = tf.random.normal([6])

print(tf.maximum(t1, t2))
print(tf.minimum(t1, t2))

print(tf.argmax(t1))

print(tf.argmax(t2, 0)) #zero is the axis (does it column wise)
#1 does it row wise

tf.Tensor([-0.41831997  0.41540504  0.4123476  -0.23639508  1.8316064   1.2520461 ], shape=(6,), dtype=float32)
tf.Tensor([-0.70973396 -0.9812629  -0.96650076 -0.54233783 -0.5950352  -0.06841824], shape=(6,), dtype=float32)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)


Can compare tensors, using math.equal and can raise powers element wise and can find many more functions in the website (library).

# Linear Algebra of Tensors

Matrix multiplication uses the linalg part. Use tf.linalg.matmul to multiply the tensors.

In [ ]:
t1 = tf.random.normal([2, 2])
t2 = tf.random.normal([2, 2])

t3 = tf.linalg.matmul(t1, t2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False)
#Can actually specify the transpose or adjoint to be true so u multiply aTb etc.
#Multiplication should be compatible in all dimensions

print(t1 @ t2) #Shortcut for multiplcation

t3 = tf.transpose(t3) #This is how you transpose

tf.Tensor(
[[2.375517   4.530316  ]
 [0.72898245 1.1020086 ]], shape=(2, 2), dtype=float32)


For 3D tensors, it's like the following

\begin{pmatrix}A & B & C\end{pmatrix}

multiplied with

\begin{pmatrix}D & E & F\end{pmatrix}

where A, B, C, D, E, F are matrices.

Thus if the dimensions are [a, b, c] and [x, y, z] then [b, c] and [y, z] represent the matrices so they must be compatible (c = y). Then a and x represent the number of matrices in each tensor.

You just multiply each entry with their corresponding entry when doing batch multiplication as a tensor is a store of information.

  \begin{pmatrix}A & B & C\end{pmatrix}
×
\begin{pmatrix}D & E & F\end{pmatrix}
=
\begin{pmatrix} AD & BE & CF\end{pmatrix}

Its only element wise multiplication (blockwise), not defined the same way as matrix multiplication with dot products of tensors.

Tensor linear algebra operations are essentially just matrix operations on each subsection. For example linalg.inv gives the inverse of each matrix in the tensor as the matrices are invertible. linalg.det gives the det of each matrix in the tensor

Can also do another type of tensor multiplication. Einstein summation.

C_ik = Σ_j A_{i,j} B_{j,k}

Also noted as ij,jk->ik. This is basically the normal way of matrix multiplication.

First argument is the equation with strings around it.
Second. Then the inputs one by one

In [ ]:
t3 = tf.einsum('ij,jk->ik', t1, t2)
print(t3)

tf.Tensor(
[[2.375517   4.530316  ]
 [0.72898245 1.1020086 ]], shape=(2, 2), dtype=float32)


But can include any kind of equation so you can define any kind of matrix multiplication. Can even make tensor multiplication like matrix multiplication instead of element wise. Its very useful if need to multiply matrices by its transpose etc, then can just tell the computer how to multiply entries instead of computing product and taking transpose. Faster.

In [ ]:
#Transpose

print(tf.einsum('ij->ji', t1)) #Dont even need an output equation

trace = tf.einsum('ii', t1)
print(trace)


s = tf.random.normal(shape=[7,5,3])
t = tf.random.normal(shape=[7,3,2])
e = tf.einsum('bij,bjk->bik', s, t)
#Element wise tensor multiplication

print(e)

tf.Tensor(
[[-0.3045729  -0.5991395 ]
 [-2.528023   -0.40803173]], shape=(2, 2), dtype=float32)
tf.Tensor(-0.71260464, shape=(), dtype=float32)
tf.Tensor(
[[[ 0.01481996 -0.6949215 ]
  [ 1.1967901  -1.777607  ]
  [ 0.13478458 -2.8568497 ]
  [-0.24946666 -2.4244761 ]
  [-0.86981887 -0.52838224]]

 [[ 0.65365493 -0.33113068]
  [-0.5295948   0.7307354 ]
  [-0.7127991   0.03078699]
  [-2.322647    1.8715788 ]
  [ 1.9996098  -1.936737  ]]

 [[-0.10779395 -0.45835787]
  [ 1.0456823   0.59483796]
  [ 1.8299899   0.75769603]
  [-0.7568112  -0.36821872]
  [-0.96130455 -0.03453024]]

 [[ 3.6588554   2.4139798 ]
  [ 4.297014    4.1317816 ]
  [-2.6158948   3.405108  ]
  [-0.7433123   0.3625856 ]
  [ 0.74624705 -0.17431287]]

 [[-3.918371    3.3144467 ]
  [ 1.958302   -1.687257  ]
  [ 3.8919334  -5.8102975 ]
  [-0.48033383  0.2087076 ]
  [-1.2562861   3.1900797 ]]

 [[-0.44323137  0.16122656]
  [ 1.0656384  -1.8349859 ]
  [ 0.60838205  0.1080319 ]
  [ 0.18937957 -0.9180374 ]
  [ 1.171059   -0.15114

Band part- copies a tensor but sets everything outside a central band to zero.

Takes input tensor as first argument, the lower number as the 2nd and the upper number as the 3rd.

num_lower- the number of subdiagonals to keep in lower half (if negative keep entire lower triangle)
num_upper- same for upper half (negative keeps entire lower triangle)

In [ ]:
tensor = tf.constant([[ 4,  1,  2, 3],
  [-1,  0,  1, 2],
  [-2, -1,  0, 1],
  [-3, -2, -1, 0]])

print(tf.linalg.band_part(tensor, 0, -1)) #Keep upper half
print(tf.linalg.band_part(tensor, 0, 0)) #diagonal

tf.Tensor(
[[4 1 2 3]
 [0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[4 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


# Tensor Flow Functions and Types of Tensors

**Expand and squeeze functions**



*   tf.expand_dims

tf.expand_dims changes the shape of the tensor by adding an extra dimension in the specified axis.

Axis = 0 -> Outer dimension, axis = 1 --> second entry, axis=-1 --> innermost dimension.

The elements are the exact same, all it is is a restructuring of the shape of the tensor.


*   tf.squeeze

tf.squeeze removes ALL dimensions of size 1 (essentially squeezing the array to remove redundancies)

You can also specify specific axes to remove the dimension of size 1



In [ ]:
t1 = tf.random.normal(
    [2, 3, 3],
    mean = 0.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)

t1 = tf.expand_dims(t1, axis=-1)
t1 = tf.squeeze(t1, axis=-1)

print(t1)

tf.Tensor(
[[[-0.60632926  0.99273664 -1.0332196 ]
  [ 0.14794634  0.8323076   1.1455222 ]
  [ 0.6604629   0.98629373 -1.2989569 ]]

 [[-0.39160913 -1.1978298  -0.08076437]
  [ 0.08145501  3.14344     0.95903295]
  [ 0.10617587  0.30995613 -0.8638287 ]]], shape=(2, 3, 3), dtype=float32)


**Reshape**

tf.reshape returns the same tensor with the same values in the same order except just restructures it and puts brackets in different places. Has to be compatible with the original shape, i.e. new shapes have to divide original shape.

Putting a negative 1 for the very last argument. For example if the desired shape is [3, 6] then putting [3, -1] will automatically fill the last segment as required.

In [ ]:
# t1 = tf.reshape(t1, [3, 6])
# print(t1)

tf.Tensor(
[[-1.043106   -0.9625143  -0.4299462  -0.62110555  1.395191   -0.13434443]
 [-0.15482023 -0.7137331   1.4525734   1.0223064  -0.33131275 -0.7067358 ]
 [-1.0760058   0.12381363 -1.2108891   0.6864058  -0.06298596 -0.61188763]], shape=(3, 6), dtype=float32)


**Concatenation**

Given some tensors, you can concatenate the entries (provided compatibility) along certain dimensions.

e.g. if you have t1, t2, t3

then you can concatenate them along axis=0 which will just give a larger tensor with each of the tensors as an entry (concatenating them on the outer axis)
etc.

tf.concat([t1,t2,t3], 1)

where 1 is the axis.

If concatenating along a new axis, for example,

tf.concat([tf.expand_dims(t, axis) for t in tensors], axis) then consider using a stack.

**STACK**

The above can be written as tf.stack(tensors, axis=axis) so if you have an array of tensors, you can concatenate all of them along a certain axis by using the stack function.

If you have n tensors, putting them into an array and putting the array as an input to the stack function, will stack these tensors together (concatenate) but add an extra dimension of n wherever the axis is.

In [ ]:
t2 = tf.random.normal([2, 3, 3])

print(tf.concat([t1, t2], 0))
print(tf.concat([t1, t2], 1))
print(tf.concat([t1, t2], 2))

print(tf.stack([t1, t2], 0))
print(tf.stack([t1, t2], 1))
print(tf.stack([t1, t2], 2))

tf.Tensor(
[[[-0.60632926  0.99273664 -1.0332196 ]
  [ 0.14794634  0.8323076   1.1455222 ]
  [ 0.6604629   0.98629373 -1.2989569 ]]

 [[-0.39160913 -1.1978298  -0.08076437]
  [ 0.08145501  3.14344     0.95903295]
  [ 0.10617587  0.30995613 -0.8638287 ]]

 [[-0.20576544  1.6690203   1.3018458 ]
  [-0.9085631   0.33456197  1.2912111 ]
  [-0.22119798  0.06077502 -0.60229415]]

 [[ 0.51765317 -0.05285897  0.91976064]
  [-0.872626   -0.6540979   0.93636554]
  [ 0.23878624 -1.2829777  -0.62534916]]], shape=(4, 3, 3), dtype=float32)
tf.Tensor(
[[[-0.60632926  0.99273664 -1.0332196 ]
  [ 0.14794634  0.8323076   1.1455222 ]
  [ 0.6604629   0.98629373 -1.2989569 ]
  [-0.20576544  1.6690203   1.3018458 ]
  [-0.9085631   0.33456197  1.2912111 ]
  [-0.22119798  0.06077502 -0.60229415]]

 [[-0.39160913 -1.1978298  -0.08076437]
  [ 0.08145501  3.14344     0.95903295]
  [ 0.10617587  0.30995613 -0.8638287 ]
  [ 0.51765317 -0.05285897  0.91976064]
  [-0.872626   -0.6540979   0.93636554]
  [ 0.23878624 

**Padding**

Padding a tensor does the following:

Suppose a tensor has n dimensions (its shape has n elements)

What padding does in each dimension of the tensor is to add a certain number of values before (in that dimension) and certain number of values after (in that dimension). The value will just be a tensor of that size full of numbers (like concatenation)

Padding takes a 2x2 tensor with N elements. Each index corresponds to a dimension and the first element says how many values before and the second, how many values after.

The value can be controlled by the constant_values=5 argument

--THE MODE CAN ALSO BE CHANGED

--Normally mode='CONSTANT'
-Other modes are reflect which just reflects the whole tensor internally and symmetric which fills the values symmetrically (here the constant_value is ignored)

In [ ]:
paddings = tf.constant([[6, 5], [4, 8], [9, 10]])

print(tf.pad(t2, paddings, mode='CONSTANT', constant_values=-1))

tf.Tensor(
[[[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]

 [[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]

 [[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]

 ...

 [[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]

 [[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ..

**GATHER FUNCTION**

tf.gather takes a tensor, a set of indices and an axis. And returns another tensor with the elements dictated by the indices in a particular axis/dimension.

tf.gather(params, indices, axis) by default axis is 0, and indices is usually a 1D array. If axis is 0, indices specifies which batches we should take of the tensor. If axis is 1, perhaps its rows, axis = 2 could be columns etc.

indices could also be a 2D array or higher in which the shape of the new tensor will have the same outline as the shape of indices. Here indices specifies the index of certain elements in the tensor to be returned in this new shape.

For example params = [A, B, C, D, E]

indices = [[2, 3], [1, 2]] would yield [[C, D], [B, C]]

If the index doesn't exist it will just fill it with zeros.

-Theres also a batch dims argument, which essentially skips a dimension if batch_dims = 1 and 2 dimensions if its 2.

batch_dims essentially aligns the batches with the indices (particularly if using gather nd, each mini tensor corresponds to a batch of the tensor)

**Gather nd**

Similar to gather but this time the index specifically specifies the shape so if the index is [[0, 2], [4, 1]] for example then the resulting tensor is the element in the 0, 2 position and the element in the 4,1 position. If the dimensions don't match then it doesn't specify a singular element but the entire dimension of elements.

In [ ]:
#1
print("----------- \n #1")
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
indices = [2, 0, 2, 5]
print(tf.gather(params, indices).numpy())
#Will return ['p2', 'p0', 'p2', 'p5']

#2
print("----------- \n #2")
print(tf.gather(params, [[2, 0], [2, 5]]).numpy())
#Will return [['p2', 'p0'], ['p2', 'p5']]

#3
print("----------- \n #3")
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(tf.gather(params, indices=[3,1]).numpy())

#4
print("----------- \n #4")
print(tf.gather_nd(
    indices=[[0, 0],
             [1, 1]],
    params = [['a', 'b'],
              ['c', 'd']]).numpy())

#5
print("----------- \n #5")
print(tf.gather_nd(
    indices = [[1],
               [0]],
    params = [['a', 'b', 'c'],
              ['d', 'e', 'f']]).numpy())


----------- 
 #1
[b'p2' b'p0' b'p2' b'p5']
----------- 
 #2
[[b'p2' b'p0']
 [b'p2' b'p5']]
----------- 
 #3
[[30. 31. 32.]
 [10. 11. 12.]]
----------- 
 #4
[b'a' b'd']
----------- 
 #5
[[b'd' b'e' b'f']
 [b'a' b'b' b'c']]


**RAGGED TENSORS**

Sometimes we may have data with not the same number of columns/rows/dimensions throughout the tensor (i.e. not rectangular). Then we cannot create a regular tensor but what we can do is create a ragged tensor which is like a non-rectangular tensor that preserves the weird shape.

In [ ]:
tensor = [[1, 2, 3],
          [3],
          [1, 7],
          [2, 1, 4]]

print(tf.ragged.constant(tensor))

<tf.RaggedTensor [[1, 2, 3], [3], [1, 7], [2, 1, 4]]>


Can also create a ragged tensor from a regular tensor by using boolean mask. This is another tensor where you put true in the exact positions you want in the ragged tensor and false otherwise.

In [ ]:
tensor = [[2, 4, 6],
          [1, 3, 5]]
mask = [[True, False, False], [True, True, False]]
print(tf.ragged.boolean_mask(tensor, mask))
#Not including ragged still works but wont produce a ragged tensor

<tf.RaggedTensor [[2], [1, 3]]>


Other ways to create a ragged tensor are from:

1. tf.RaggedTensor.from_row_splits
-Start with an array of values
-specify an array called row_splits which specifies the indices we should split the rows

For example row_splits=[0, 4, 4, 7, 8, 8] specifies that the first element will contain indices 0 up to but not including 4. Then from 4 to 4 which will be empty. Then from 4 up to 7. Then from 7 to 8, and finally 8 to 8 which is empty.

2. tf.RaggedTensor.from_row_limits

row_lengths=[4, 4, 7, 8, 8]

Works very similarly as above except now they're limits so first one goes up to 4. Then from 4 to 4 then from 4 up to 7 etc.

3. tf.RaggedTensor.from_row_lengths

row_lengths=[4, 0, 3, 1, 0]

Now the first element is of length 4, the next of length 0, etc.

In [ ]:
print(tf.RaggedTensor.from_row_splits(
      values=[3, 1, 4, 1, 5, 9, 2, 6],
      row_splits=[0, 4, 4, 7, 8, 8]))

print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


**SPARSE TENSORS**

Alot of the time, we will have data containing many zeros and its more efficient to use sparse tensors as they're optimized when there are zeros to skip calculation.

indices specifies the indices containing non-zero values (each element is an index). Values give you the corresponding values at each index.

dense_shape is the tensor shape.

In [ ]:
tensor_sparse = tf.sparse.SparseTensor(indices = [[1,1], [3, 4]], values = [11, 56], dense_shape = [5,6])
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


**STRING TENSORS**

Special methods to deal with strings

In [ ]:
tensor_string = tf.constant(["H", "A", "P"])
print(tf.strings.join(tensor_string, separator="^")) #joins all the string
#Many more methods

tf.Tensor(b'H^A^P', shape=(), dtype=string)


**VARIABLES**

Our tensor values will need to be updated throughout so use variable instead of constant to represent tensors. Most tensor operations work on variables except reshaping. Pass in any tensor into the variable argument. The argument consists of a lot of hidden features e.g. trainable=None which says if it can be modified during training.

You can assign other values to tensors without changing shape. assign_add and assign_sub adds to another tensor elementwise

Variables are backed by tensors so operations on them are done on the backing tensors. Duplicating them creates a copy of the tensor, they will not share the same memory thus duplicated variables are not equal.

In [ ]:
x = tf.Variable([2, 3, 5])
x.assign([1, 4, 7])
print(x)
x.assign_add([1, 3, 5])
print(x)
x.assign_sub([2, 2, 0])
print(x)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 4, 7], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 2,  7, 12], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 0,  5, 12], dtype=int32)>


You can also choose which device you want your variable to be in (cpu, gpu, tpu) to check which one you're using in colab, click runtime and change runtime type.

To be in a specific device do the following:

In [ ]:
with tf.device('CPU:0'): #Replace CPU with GPU if u want
  x = tf.variable(0.2)

print(x.device) #Gives the device

AttributeError: module 'tensorflow' has no attribute 'variable'